### PR TITLE
Update to better pull handling and dynamic update interval

### PR DESCRIPTION
**Pull request by ufozone**
(Minor) Features:
- Update to better API pull handling
- Update to dynamic update interval

### CODE REVIEW

**Review by sHedC — APPROVED** [review]
I feel very lazy in comparison to how much you have done.  Looking really good.

**Comment by sHedC** [comment]
> Today I had to update the config and options flow of my integration, because I want to integrate a camera entity starting next week, which will cause some settings in the flow. In doing so, I basically took your menu framework and added logic to it.

Is this part of Ambrogio Robots/ Camera entity?

I was going to re-write the config and options flow so maybe you can send it over I can merge it?

**Comment by sHedC** [comment]
> I'm still learning a lot of Python and Home Assistant integrations.

I have only done one integration with both HA and Python so I know what you mean.

**Comment by ufozone** [comment]
You can find my Options and Config Flow here:
https://github.com/ufozone/ha-zcs-mower/blob/main/custom_components/zcsmower/config_flow.py

I think the following breaking changes will be necessary:
- Change Entity Name and Unique ID to {platform}.{robot_imei}_{entity_key} . This way, when renaming the robot, no new entity will be created and the old one will be abandoned.
- I moved the configurations from config_entry.options to config_entry.data, because otherwise I always got problems with saving.

**Comment by sHedC** [comment]
I will check it out I randomly set stuff just to make it work, so yes should have better name and id's.  I will merge this one into mine, although will be a bit slow as works busy.

**Pull request merged**
